name: ci

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim:
          - v0.10.4
          - stable
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: rhysd/action-setup-vim@febef33995d6649302e9d88dda81e071b68f16a7
        with:
          version: ${{ matrix.neovim }}
          neovim: true
      - run: ./scripts/test
